config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :friends
  get 'home/index'
  get 'home/about'
  # root 'home#index'
  root 'friends#index' #inside the friends_Controller, use index route
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # before doing anything in this controller, if the user is not authenticated then dont let them do anything except viewing index and show pages. (means cant do new,edit etc)
  before_action :authenticate_user!, except:[:index, :show]
  # before_action :authenticate_user!

  # only these actions will be permitted if the user is correct user 
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # created a new friend for @friend DB
    # @friend = Friend.new

    # associating current_user with the new friend 
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # created new method
  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not authorized for this action !! " if @friend.nil?
    # redirect error notice is the @friend is nill i.e not matching with the DB entry.
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:name, :email, :phone, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class:"form-control", placeholder:"Enter your name here" %>
  </div>

  <div class="form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class:"form-control", placeholder:"Enter your E-mail ID here" %>
  </div>

  <div class="form-group">
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, class:"form-control", placeholder:"Enter your phone number here" %>
  </div>
  <div class="form-group">
    <%= form.number_field :user_id, id: :friend_user_id , class:"form-control", placeholder:"User ID", value:current_user.id, type: :hidden %>
  </div>
  <%# current_user.inspect %>
  <%# current_user.id %>

  <div>
    <%= form.submit class:"btn btn-success" %> 
    <%# Remeber no comma here to put for class if no text %>

  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>Name:</strong>
    <%= friend.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class:"btn btn-primary" %>

  <%= button_to friend_path(@friend), method: :delete, class:"btn my-4 btn-danger" do %>
    Delete
  <% end %>

  <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>

</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>

<h1 class="my-3">Friends List</h1>

<table class="table table-striped table-success table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>E-Mail</th>
      <th>Phone</th>
      <th>User ID</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <% if friend.user == current_user %>
      <tr>
        <td><%= link_to friend.name, friend %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.user_id %></td>

        <td><%= link_to "Edit", edit_friend_path(friend), class:"btn btn-sm btn-primary" %></td>
        <td><%= button_to friend_path(friend), method: :delete, class:"btn btn-sm btn-danger" do %>
          Delete
        <% end %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
    
<br>

<%= link_to "New friend", new_friend_path, class:"btn btn-secondary" %>

<% else %>

<h1>Hello</h1>
<h3>You're not signed in yet</h3>

<% end %>

app/views/friends/new.html.erb
<h1 class="my-2">Add a New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path, class:"btn btn-dark" %>
</div>

app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @friend.name %></h1>
  <p class="lead"><%= @friend.email %></p>
  <p><%= @friend.phone %></p>
  <hr class="my-4">
  <%= link_to "Edit", edit_friend_path(@friend), class:"btn btn-primary m-1 mx-0" %> 
  <%= link_to "Back", friends_path, class:"btn btn-secondary m-1" %>

  <%= button_to "Destroy this friend", @friend, method: :delete, class:"btn btn-danger m-1 mx-0" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-dark navbar-expand-lg bg-dark">
  <div class="container-fluid">
  <%= link_to "Friend App", root_path, class:"navbar-brand" %>
    <%# <a class="navbar-brand" href="#">Friends App</a> %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to "Home", root_path, class:"nav-link" %>
          <%# <a class="nav-link active" aria-current="page" href="#">Home</a> %>
        </li>
        <li class="nav-item">
        <%= link_to "About", home_about_path, class:"nav-link"%>
          <%# <a class="nav-link" href="#">Link</a> %>
        </li>
        <li class="nav-item">

        <% if user_signed_in? %>
          <li class="nav-item">
          <%= link_to "Friends", friends_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
          <%= link_to "Add Friend", new_friend_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link"%>
            <%# <a class="nav-link" href="#">Link</a> %>
          </li>
          <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete , class:"nav-link"%>
            <%# <a class="nav-link" href="#">Link</a> %>
          </li>

        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
            <%# <a class="nav-link" href="#">Link</a> %>
          </li>
          <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link"%>
            <%# <a class="nav-link" href="#">Link</a> %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us</h1>

app/views/home/index.html.erb
<h1>Home/index</h1>

<p>Find me in app/views/home/index.html.erb</p>

<h6>Created 1st ROR webpage yoooooooo</h6>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
<%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Friends App</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>

  <%= render "home/header" %>
  <%# render tells rails that it's a partial doc so treat it like that instead of typeing whole _header.html.erb%>
    <div class="container">
    <br/>
    <% if notice %>
    <%= render "layouts/alerts" %>
    <% end %>
    <br/>
      <%= yield %>
      <%# this yield tag is the index.html %>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>